config/routes.rb
MovieApp::Application.routes.draw do
    root to: 'movie_app#index'

    resources :movie_app
end

app/models/movieapp.rb
class Movieapp < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/movie_app_controller.rb
class MovieAppController < ApplicationController

def index
	@movieapps = Movieapp.all
end

def show
	@movieapps = Movieapp.find(params[:id])
end




end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movieapp_helper.rb
module MovieappHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MovieApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/movie_app/index.html.erb
<h1> Welcome to Retflix. </h1>
<h3> See all of the movies below </h3>

<ul>
<% @movieapps.each do |details| %>
<li>
	<%= details.name %> :
	<%= image_tag( details.image ) %>
	<%= link_to "Movie Details", movie_app_path(details.id) %>
</li>
<% end %>


</ul>

app/views/movie_app/show.html.erb
<h2> Movie Details: </h2>

<%= @movieapps.name %>
<%= @movieapps.description %>

<%= link_to "Back to Movie List", movie_app_index_path %>